<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestingDemoSuites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>58a7e7c5-d38b-4c13-ad17-a43fcde908b7</testSuiteGuid>
   <testCaseLink>
      <guid>4b09edb6-d9cb-4cb3-a674-8a5d467a9606</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTestDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cf4c30f2-f2eb-4d07-b403-466552fea109</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>cf4c30f2-f2eb-4d07-b403-466552fea109</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CountryCode</value>
         <variableId>fac5ad7a-6e6c-498a-9d1e-49d3eb8dbf25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cf4c30f2-f2eb-4d07-b403-466552fea109</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Capital</value>
         <variableId>0b04d243-2a5a-43c6-b7dc-11d33383a8c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cf4c30f2-f2eb-4d07-b403-466552fea109</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Currency1</value>
         <variableId>d7e7d8ea-4897-4732-bb54-a4a2142396e2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
